=== Zarconium/Senior/CS119.2 ESP/Inventory Query Functional Area/INVQRY.XSD
<?xml version="1.0" encoding="Windows-1252"?>
<!-- Copyright 1994-2010 SYSPRO Ltd.-->
<!--
     Schema for Inventory Query Business Object
-->
<xsd:schema elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="Filter">
    <xsd:complexType mixed="false">
      <xsd:sequence>
        <xsd:element ref="Warehouse" minOccurs="0"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="MultiMediaImageType" type="xsd:string">
    <xsd:annotation>
      <xsd:documentation>Image type to retrieve (for example: GIF, JPG)</xsd:documentation>
    </xsd:annotation>
  </xsd:element>
  <xsd:element name="IncludeCustomForms" default="N">
    <xsd:annotation>
      <xsd:documentation>Do you wish to include fields from custom forms ? (N - No, Y - Yes,)</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:enumeration value="N"/>
        <xsd:enumeration value="Y"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="IncludeBins" default="N">
    <xsd:annotation>
      <xsd:documentation>Do you wish to include multiple bins ? (N - No, Y - Yes Z - Include zero qty on hand bins)</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:enumeration value="N"/>
        <xsd:enumeration value="Y"/>
        <xsd:enumeration value="Z"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="IncludeHistory" default="Y">
    <xsd:annotation>
      <xsd:documentation>Do you wish to include history ? (Y - Yes, N - No)</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:enumeration value="Y"/>
        <xsd:enumeration value="N"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="IncludeLots" default="N">
    <xsd:annotation>
      <xsd:documentation>Do you wish to include lots ? (N - No, Y - Yes, Z - Include zero qty on hand lots)</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:enumeration value="N"/>
        <xsd:enumeration value="Y"/>
        <xsd:enumeration value="Z"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="IncludeMovementAdjustments" default="Y">
    <xsd:annotation>
      <xsd:documentation>Do you wish to include adjustments ? (Y - Yes, N - No)</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:enumeration value="Y"/>
        <xsd:enumeration value="N"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="IncludeMovementBinTransfers" default="Y">
    <xsd:annotation>
      <xsd:documentation>Do you wish to include bin transfers ? (Y - Yes, N - No)</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:enumeration value="Y"/>
        <xsd:enumeration value="N"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="IncludeMovementCostChanges" default="Y">
    <xsd:annotation>
      <xsd:documentation>Do you wish to include cost changes ? (Y - Yes, N - No)</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:enumeration value="Y"/>
        <xsd:enumeration value="N"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="IncludeMovementCostMods" default="Y">
    <xsd:annotation>
      <xsd:documentation>Do you wish to include cost modifications ? (Y - Yes, N - No)</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:enumeration value="Y"/>
        <xsd:enumeration value="N"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="IncludeMovementCreditNotes" default="Y">
    <xsd:annotation>
      <xsd:documentation>Do you wish to include credit notes ? (Y - Yes, N - No)</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:enumeration value="Y"/>
        <xsd:enumeration value="N"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="IncludeMovementDebitNotes" default="Y">
    <xsd:annotation>
      <xsd:documentation>Do you wish to include debit note movements ? (Y - Yes, N - No)</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:enumeration value="Y"/>
        <xsd:enumeration value="N"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="IncludeMovementDispatchNotes" default="Y">
    <xsd:annotation>
      <xsd:documentation>Do you wish to include dispatch note movements? (Y - Yes, N - No)</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:enumeration value="Y"/>
        <xsd:enumeration value="N"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="IncludeMovementInvoices" default="Y">
    <xsd:annotation>
      <xsd:documentation>Do you wish to include invoice movements? (Y - Yes, N - No)</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:enumeration value="Y"/>
        <xsd:enumeration value="N"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="IncludeMovementIssues" default="Y">
    <xsd:annotation>
      <xsd:documentation>Do you wish to include issue movements ? (Y - Yes, N - No)</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:enumeration value="Y"/>
        <xsd:enumeration value="N"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="IncludeMovementPhysical" default="Y">
    <xsd:annotation>
      <xsd:documentation>Do you wish to include physical movements ? (Y - Yes, N - No)</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:enumeration value="Y"/>
        <xsd:enumeration value="N"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="IncludeMovementReceipts" default="Y">
    <xsd:annotation>
      <xsd:documentation>Do you wish to include receipt movements ? (Y - Yes, N - No)</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:enumeration value="Y"/>
        <xsd:enumeration value="N"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="IncludeEcc" default="Y">
    <xsd:annotation>
      <xsd:documentation>Do you wish to include ECC ? (Y - Yes, N - No). The default is Y.</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:enumeration value="Y"/>
        <xsd:enumeration value="N"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="IncludeMovements" default="N">
    <xsd:annotation>
      <xsd:documentation>Do you wish to include movements ? (N - No, Y - Yes)</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:enumeration value="N"/>
        <xsd:enumeration value="Y"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="IncludeMovementTransfers" default="Y">
    <xsd:annotation>
      <xsd:documentation>Do you wish to include transfer movements ? (Y - Yes, N - No)</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:enumeration value="Y"/>
        <xsd:enumeration value="N"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="IncludeSerials" default="N">
    <xsd:annotation>
      <xsd:documentation>Do you wish to include serial numbers ? (N - No, Y - Yes, Z=Include zero qty on hand serials)</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:enumeration value="N"/>
        <xsd:enumeration value="Y"/>
        <xsd:enumeration value="Z"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="IncludeNarrations" default="Y">
    <xsd:annotation>
      <xsd:documentation>Indicates whether narrations should be returned. (Y - Yes and N = No). If no value is supplied then a default value of 'Y' will be used. </xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:minLength value="0"/>
        <xsd:maxLength value="1"/>
        <xsd:whiteSpace value="preserve"/>
        <xsd:enumeration value="Y"/>
        <xsd:enumeration value="N"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="ReturnNarrationsinBlock" default="N">
    <xsd:annotation>
      <xsd:documentation>Indicates whether narrations should be returned combined in a block. (N - No and Y - Yes). If no value is supplied then a default value of 'N' will be used. </xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:whiteSpace value="preserve"/>
        <xsd:minLength value="0"/>
        <xsd:maxLength value="1"/>
        <xsd:enumeration value="N"/>
        <xsd:enumeration value="Y"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="Key">
    <xsd:annotation>
      <xsd:documentation>The key to use for this query.</xsd:documentation>
    </xsd:annotation>
    <xsd:complexType mixed="false">
      <xsd:sequence>
        <xsd:element ref="StockCode"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="MovementDateSequence" default="A">
    <xsd:annotation>
      <xsd:documentation>The sequence of the returned records (A - Ascending date sequence, D - Descending date sequence)</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:enumeration value="A"/>
        <xsd:enumeration value="D"/>
      </xsd:restriction>
    </xsd:simpleType>
    <!--<xsd:SimpleType>
      <xsd:simpleContent>
        <xsd:restriction base="xsd:string">
          <xsd:enumeration value="A"/>
          <xsd:enumeration value="D"/>
        </xsd:restriction>
      </xsd:simpleContent>
    </xsd:SimpleType> -->
  </xsd:element>
  <xsd:element name="MaxNumberMovements">
    <xsd:annotation>
      <xsd:documentation>The maximum number of Movement entries to return (enter a value between 0 and 99999999 where 0 / blank returns all records)</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:minLength value="1"/>
        <xsd:maxLength value="8"/>
        <xsd:whiteSpace value="preserve"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="MovementStartDate" type="xsd:date">
    <xsd:annotation>
      <xsd:documentation>The date from which to extract movements</xsd:documentation>
    </xsd:annotation>
  </xsd:element>
  <xsd:element name="Option">
    <xsd:annotation>
      <xsd:documentation>The list of options</xsd:documentation>
    </xsd:annotation>
    <xsd:complexType mixed="false">
      <xsd:sequence>
        <xsd:element ref="MultiMediaImageType" minOccurs="0"/>
        <xsd:element ref="IncludeHistory" minOccurs="0"/>
        <xsd:element ref="IncludeBins" minOccurs="0"/>
        <xsd:element ref="IncludeLots" minOccurs="0"/>
        <xsd:element ref="IncludeSerials" minOccurs="0"/>
        <xsd:element ref="IncludeMovements" minOccurs="0"/>
        <xsd:element ref="MovementDateSequence" minOccurs="0"/>
        <xsd:element ref="MovementStartDate" minOccurs="0"/>
        <xsd:element ref="MaxNumberMovements" minOccurs="0"/>
        <xsd:element ref="IncludeCustomForms" minOccurs="0"/>
        <xsd:element ref="IncludeMovementIssues" minOccurs="0"/>
        <xsd:element ref="IncludeMovementTransfers" minOccurs="0"/>
        <xsd:element ref="IncludeMovementReceipts" minOccurs="0"/>
        <xsd:element ref="IncludeMovementPhysical" minOccurs="0"/>
        <xsd:element ref="IncludeMovementAdjustments" minOccurs="0"/>
        <xsd:element ref="IncludeMovementCostChanges" minOccurs="0"/>
        <xsd:element ref="IncludeMovementCostMods" minOccurs="0"/>
        <xsd:element ref="IncludeMovementBinTransfers" minOccurs="0"/>
        <xsd:element ref="IncludeMovementInvoices" minOccurs="0"/>
        <xsd:element ref="IncludeMovementCreditNotes" minOccurs="0"/>
        <xsd:element ref="IncludeMovementDebitNotes" minOccurs="0"/>
        <xsd:element ref="IncludeMovementDispatchNotes" minOccurs="0"/>
        <xsd:element ref="IncludeEcc" minOccurs="0"/>
        <xsd:element ref="IncludeApprovedManuf" minOccurs="0"/>
        <xsd:element ref="IncludeNarrations"/>
        <xsd:element ref="ReturnNarrationsinBlock"/>
        <xsd:element ref="XslStylesheet" minOccurs="0"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="Query">
    <xsd:annotation>
      <xsd:documentation>The root element</xsd:documentation>
    </xsd:annotation>
    <xsd:complexType mixed="false">
      <xsd:sequence>
        <xsd:element ref="Key"/>
        <xsd:element ref="Option" minOccurs="0"/>
        <xsd:element ref="Filter" minOccurs="0"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="StockCode">
    <xsd:annotation>
      <xsd:documentation>The stock code to use for the query</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:maxLength value="30"/>
        <xsd:whiteSpace value="preserve"/>
        <xsd:minLength value="1"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="Warehouse">
    <xsd:annotation>
      <xsd:documentation>List or Range of warehouses separated by commas.</xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:attribute name="FilterType" use="optional">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:length value="1"/>
            <xsd:enumeration value="R"/>
            <xsd:enumeration value="L"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
      <xsd:attribute name="FilterValue" use="optional">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string"/>
        </xsd:simpleType>
      </xsd:attribute>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="XslStylesheet">
    <xsd:annotation>
      <xsd:documentation>The Stylesheet to be applied</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:whiteSpace value="preserve"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="IncludeApprovedManuf" default="Y">
    <xsd:annotation>
      <xsd:documentation>Do you wish to include a list of approved manufacturers for this stock code? (Y - Yes, N - No)</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:enumeration value="Y"/>
        <xsd:enumeration value="N"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
</xsd:schema>

=== Zarconium/Senior/CS119.2 ESP/Inventory Query Functional Area/INVQRY.XML
<?xml version="1.0" encoding="Windows-1252"?>
<!-- Copyright 1994-2010 SYSPRO Ltd.-->
<!-- 
     This is an example XML instance to demonstrate
     use of the Inventory Query Business Object
-->
<Query xmlns:xsd="http://www.w3.org/2000/10/XMLSchema-instance" xsd:noNamespaceSchemaLocation="INVQRY.XSD">
  <Key>
    <StockCode><![CDATA[A100]]></StockCode>
  </Key>
  <Option>
    <MultiMediaImageType>GIF</MultiMediaImageType>
    <IncludeHistory>Y</IncludeHistory>
    <IncludeBins>Y</IncludeBins>
    <IncludeLots>Y</IncludeLots>
    <IncludeSerials>Y</IncludeSerials>
    <IncludeMovements>Y</IncludeMovements>
    <MovementDateSequence>A</MovementDateSequence>
    <MovementStartDate>2001-01-12</MovementStartDate>
    <MaxNumberMovements>100</MaxNumberMovements>
    <IncludeCustomForms>N</IncludeCustomForms>
    <IncludeMovementIssues>Y</IncludeMovementIssues>
    <IncludeMovementTransfers>Y</IncludeMovementTransfers>
    <IncludeMovementReceipts>Y</IncludeMovementReceipts>
    <IncludeMovementPhysical>Y</IncludeMovementPhysical>
    <IncludeMovementAdjustments>Y</IncludeMovementAdjustments>
    <IncludeMovementCostChanges>Y</IncludeMovementCostChanges>
    <IncludeMovementCostMods>Y</IncludeMovementCostMods>
    <IncludeMovementBinTransfers>Y</IncludeMovementBinTransfers>
    <IncludeMovementInvoices>Y</IncludeMovementInvoices>
    <IncludeMovementCreditNotes>Y</IncludeMovementCreditNotes>
    <IncludeMovementDebitNotes>Y</IncludeMovementDebitNotes>
    <IncludeMovementDispatchNotes>Y</IncludeMovementDispatchNotes>
    <IncludeEcc>Y</IncludeEcc>
    <IncludeApprovedManuf>Y</IncludeApprovedManuf>
    <IncludeNarrations>Y</IncludeNarrations>
    <ReturnNarrationsinBlock>N</ReturnNarrationsinBlock>
    <XslStylesheet/>
  </Option>
  <Filter>
    <Warehouse FilterType="L" FilterValue="S,N,E"/>
  </Filter>
</Query>
