=== Zarconium/Senior/CS119.2 ESP/Inventory Posting Functional Area/Cost Modification/INVTMMDOC.XSD
<?xml version="1.0" encoding="Windows-1252"?>
<!-- Copyright 1994-2010 SYSPRO Ltd.-->
<!--
     Schema for Inventory Cost Modifications Business Object
-->
<xsd:schema elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="eSignature">
    <xsd:annotation>
      <xsd:documentation>This element contains the GUID of the current process required to authenticate the transaction when Electronic Signatures are in use.</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:minLength value="0"/>
        <xsd:maxLength value="38"/>
        <xsd:whiteSpace value="preserve"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="Item">
    <xsd:annotation>
      <xsd:documentation>This is the top element for all data required to post the transaction.</xsd:documentation>
    </xsd:annotation>
    <xsd:complexType mixed="false">
      <xsd:sequence>
        <xsd:element ref="Journal" minOccurs="0"/>
        <xsd:element ref="Warehouse"/>
        <xsd:element ref="StockCode"/>
        <xsd:element ref="Quantity" minOccurs="0"/>
        <xsd:element ref="UnitOfMeasure" minOccurs="0"/>
        <xsd:element ref="Units" minOccurs="0"/>
        <xsd:element ref="Pieces" minOccurs="0"/>
        <xsd:element ref="PreviousCost" minOccurs="0"/>
        <xsd:element ref="NewUnitCost" minOccurs="0"/>
        <xsd:element ref="NewTotalCost" minOccurs="0"/>
        <xsd:element ref="Reference" minOccurs="0"/>
        <xsd:element ref="Notation" minOccurs="0"/>
        <xsd:element ref="LedgerCode" minOccurs="0"/>
        <xsd:element ref="PasswordForLedgerCode" minOccurs="0"/>
        <xsd:element ref="eSignature" minOccurs="0"/>
        <xsd:element ref="AnalysisEntry" minOccurs="0"/>
        <xsd:element ref="AnalysisLineEntry" minOccurs="0"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="Journal">
    <xsd:annotation>
      <xsd:documentation>This is the journal number to which the transaction journal entries will be added. It must be valid for the current posting period and warehouse and may not have been printed already. If not supplied, a new journal will be created.</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:whiteSpace value="preserve"/>
        <xsd:minLength value="0"/>
        <xsd:maxLength value="5"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="LedgerCode">
    <xsd:annotation>
      <xsd:documentation>This element is only used if Inventory is integrated to General Ledger or requires a Report,  and ledger codes are required for this type of inventory transaction. If entered and used, it must be a valid ledger code, and must not be on hold.</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:whiteSpace value="preserve"/>
        <xsd:minLength value="0"/>
        <xsd:maxLength value="15"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="NewTotalCost">
    <xsd:annotation>
      <xsd:documentation>New total cost of the specified quantity. The new unit cost will be calculated. Only one of the costs may be supplied. The transaction will be rejected if both are supplied or if the cost supplied is zero and the 'IgnoreWarnings' parameter is set to 'N'.</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:whiteSpace value="preserve"/>
        <xsd:minLength value="0"/>
        <xsd:maxLength value="16"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="NewUnitCost">
    <xsd:annotation>
      <xsd:documentation>New unit cost of the specified quantity. Only one of the costs may be supplied. The transaction will be rejected if both are supplied or if the cost supplied is zero and the 'IgnoreWarnings' parameter is set to 'N'.</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:whiteSpace value="preserve"/>
        <xsd:minLength value="0"/>
        <xsd:maxLength value="16"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="Notation">
    <xsd:annotation>
      <xsd:documentation>This element is optional.</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:whiteSpace value="preserve"/>
        <xsd:minLength value="0"/>
        <xsd:maxLength value="45"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="Pieces">
    <xsd:annotation>
      <xsd:documentation>If stock code is a unit-qty type stock code and quantity element is not supplied, the quantity of the transaxtion must be supplied as units and pieces. At least one of these elements must be supplied.</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:whiteSpace value="preserve"/>
        <xsd:minLength value="0"/>
        <xsd:maxLength value="3"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="PostInvCostModification">
    <xsd:annotation>
      <xsd:documentation>This is the root element.</xsd:documentation>
    </xsd:annotation>
    <xsd:complexType mixed="false">
      <xsd:sequence>
        <xsd:element ref="Item" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="PasswordForLedgerCode">
    <xsd:annotation>
      <xsd:documentation>If ledger codes require a password, this element must contain the relevant password for the specified ledger code.</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:whiteSpace value="preserve"/>
        <xsd:minLength value="0"/>
        <xsd:maxLength value="30"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="PreviousCost">
    <xsd:annotation>
      <xsd:documentation>This element indicates the cost of the quantity specified. If not supplied, it defaults to the last cost for the warehouse.</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:whiteSpace value="preserve"/>
        <xsd:minLength value="1"/>
        <xsd:maxLength value="16"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="Quantity">
    <xsd:annotation>
      <xsd:documentation>This element is mandatory if stock code is not a unit-qty type stock code. It it is and this element is supplied, the units and pieces elements must NOT be supplied.</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:whiteSpace value="preserve"/>
        <xsd:minLength value="0"/>
        <xsd:maxLength value="11"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="Reference">
    <xsd:annotation>
      <xsd:documentation>This element is optional.</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:whiteSpace value="preserve"/>
        <xsd:minLength value="0"/>
        <xsd:maxLength value="9"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="StockCode">
    <xsd:annotation>
      <xsd:documentation>This element is mandatory and must contain a valid stock code stocked in the specified warehouse.</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:whiteSpace value="preserve"/>
        <xsd:minLength value="1"/>
        <xsd:maxLength value="30"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="UnitOfMeasure">
    <xsd:annotation>
      <xsd:documentation>If quantity is supplied in a unit of measure different to the stocking unit of measure, this element may be supplied to indicate the alternate unit of measure.</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:whiteSpace value="preserve"/>
        <xsd:minLength value="0"/>
        <xsd:maxLength value="3"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="Units">
    <xsd:annotation>
      <xsd:documentation>If stock code is a unit-qty type stock code and quantity element is not supplied, the quantity of the transaxtion must be supplied as units and pieces. At least one of these elements must be supplied.</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:whiteSpace value="preserve"/>
        <xsd:minLength value="0"/>
        <xsd:maxLength value="7"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="Warehouse">
    <xsd:annotation>
      <xsd:documentation>This element is mandatory and must stock the specified stock code.</xsd:documentation>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:whiteSpace value="preserve"/>
        <xsd:minLength value="1"/>
        <xsd:maxLength value="2"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
  <xsd:element name="AnalysisEntry">
    <xsd:annotation>
      <xsd:documentation>If an analysis entry number has been assigned to this detail line, then use this element to store the analysis entry number. If Analysis Line entry is passed then that will overwrite and analysis number supplied in the AnalysisEntry element. </xsd:documentation>
    </xsd:annotation>
  </xsd:element>
  <xsd:element name="AnalysisLineEntry">
    <xsd:annotation>
      <xsd:documentation>If IgnoreAnalysis is set to 'Y" this node and all it's elements are ignored. If you are supplying your own AnalysisEntry Number ensure that you have set IgnoreAnalysis to "Y"</xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="AnalysisCode1">
          <xsd:annotation>
            <xsd:documentation>You can specify an analysis code 1 for the analysis entry you are createing </xsd:documentation>
          </xsd:annotation>
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:maxLength value="10"/>
              <xsd:whiteSpace value="preserve"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="AnalysisCode2">
          <xsd:annotation>
            <xsd:documentation>You can specify and analysis code 2 for the analysis entry you are creating</xsd:documentation>
          </xsd:annotation>
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:maxLength value="10"/>
              <xsd:whiteSpace value="preserve"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="AnalysisCode3">
          <xsd:annotation>
            <xsd:documentation>You can specify an analysis code 3 for the analysis entry you are creating</xsd:documentation>
          </xsd:annotation>
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:maxLength value="10"/>
              <xsd:whiteSpace value="preserve"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="AnalysisCode4">
          <xsd:annotation>
            <xsd:documentation>You can specify and analysis code 4 for the analysis entry you are creating</xsd:documentation>
          </xsd:annotation>
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:maxLength value="10"/>
              <xsd:whiteSpace value="preserve"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="AnalysisCode5">
          <xsd:annotation>
            <xsd:documentation>You can specify and analysis code 5 for the analysis entry you are createing</xsd:documentation>
          </xsd:annotation>
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:maxLength value="10"/>
              <xsd:whiteSpace value="preserve"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="StartDate">
          <xsd:annotation>
            <xsd:documentation>You can specify a start date for the analysis entry you are creating</xsd:documentation>
          </xsd:annotation>
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:maxLength value="10"/>
              <xsd:whiteSpace value="preserve"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="EndDate">
          <xsd:annotation>
            <xsd:documentation>You can specify an end date for the analysis entry you are creating</xsd:documentation>
          </xsd:annotation>
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:maxLength value="10"/>
              <xsd:whiteSpace value="preserve"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="EntryAmount">
          <xsd:annotation>
            <xsd:documentation>You must specify and entry amount for the analysis entry you are creating.If the entry amount supplied does not agree with the calculated transaction value at runtime, the entry amount will be overwritten with the transaction value.</xsd:documentation>
          </xsd:annotation>
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:maxLength value="16"/>
              <xsd:whiteSpace value="preserve"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="Comment">
          <xsd:annotation>
            <xsd:documentation>You can enter a comment for the analysis entry you are creating</xsd:documentation>
          </xsd:annotation>
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:maxLength value="60"/>
              <xsd:whiteSpace value="preserve"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== Zarconium/Senior/CS119.2 ESP/Inventory Posting Functional Area/Cost Modification/INVTMMDOC.XML
<?xml version="1.0" encoding="Windows-1252"?>
<!-- Copyright 1994-2010 SYSPRO Ltd.-->
<!-- 
     This is an example XML instance to demonstrate
     use of the Inventory Cost Modifications Business Object
-->
<PostInvCostModification xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="INVTMMDOC.XSD">
  <Item>
    <Journal/>
    <Warehouse>E</Warehouse>
    <StockCode>A100</StockCode>
    <Quantity>2</Quantity>
    <UnitOfMeasure/>
    <Units/>
    <Pieces/>
    <PreviousCost>355.00000</PreviousCost>
    <NewUnitCost>375.00000</NewUnitCost>
    <NewTotalCost/>
    <Reference>Cost mod</Reference>
    <Notation>Cost modification note</Notation>
    <LedgerCode>30-5610</LedgerCode>
    <PasswordForLedgerCode/>
    <eSignature/>
    <AnalysisEntry/>
    <AnalysisLineEntry>
      <AnalysisCode1>Air</AnalysisCode1>
      <AnalysisCode2>Conf</AnalysisCode2>
      <AnalysisCode3>East</AnalysisCode3>
      <AnalysisCode4/>
      <AnalysisCode5/>
      <StartDate/>
      <EndDate/>
      <EntryAmount>100</EntryAmount>
      <Comment>Analysis entry details</Comment>
    </AnalysisLineEntry>
  </Item>
</PostInvCostModification>
