=== Zarconium/Senior/CS119.2 ESP/Inventory Posting Functional Area/Transfers/Transfer OUT/INVTMODOC.XSD
<?xml version="1.0" encoding="Windows-1252"?>
<!-- Copyright 1994-2010 SYSPRO Ltd.-->
<!--
     Schema for Inventory Warehouse Transfer Out Business Object
-->
<xsd:schema elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="FromBin">
		<xsd:annotation>
			<xsd:documentation>This element is mandatory if multiple bins are installed  and must be exist in 'From' warehouse.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:whiteSpace value="preserve"/>
				<xsd:minLength value="0"/>
				<xsd:maxLength value="6"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	<xsd:element name="eSignature">
		<xsd:annotation>
			<xsd:documentation>This element contains the GUID of the current process required to authenticate the transaction when Electronic Signatures are in use.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:minLength value="0"/>
				<xsd:maxLength value="38"/>
				<xsd:whiteSpace value="preserve"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	<xsd:element name="FromWarehouse">
		<xsd:annotation>
			<xsd:documentation>This element is mandatory and must stock specified stock item.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:whiteSpace value="preserve"/>
				<xsd:minLength value="1"/>
				<xsd:maxLength value="2"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	<xsd:element name="Immediate" default="N">
		<xsd:annotation>
			<xsd:documentation>If processing an immediate warehouse transfer, this element must contain 'Y'. If this is not supplied or is set to 'N' a normal transfer OUT transaction is processed.Defaults to 'N'. Valid values are 'N' and 'Y'.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:whiteSpace value="preserve"/>
				<xsd:minLength value="0"/>
				<xsd:maxLength value="1"/>
				<xsd:enumeration value="N"/>
				<xsd:enumeration value="Y"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	<xsd:element name="PostInvWhTransferOut">
		<xsd:annotation>
			<xsd:documentation>This is the root element.</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType mixed="false">
			<xsd:sequence>
				<xsd:element ref="Item" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="Item">
		<xsd:annotation>
			<xsd:documentation>This is the top element fo all data required for the transaction.</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType mixed="false">
			<xsd:sequence>
				<xsd:element ref="Journal" minOccurs="0"/>
				<xsd:element ref="Immediate" minOccurs="0"/>
				<xsd:element ref="NoDestination" minOccurs="0"/>
				<xsd:element ref="FromWarehouse"/>
				<xsd:element ref="FromBin" minOccurs="0"/>
				<xsd:element ref="StockCode"/>
				<xsd:element ref="Version" minOccurs="0"/>
				<xsd:element ref="Release" minOccurs="0"/>
				<xsd:element ref="Quantity" minOccurs="0"/>
				<xsd:element ref="UnitOfMeasure" minOccurs="0"/>
				<xsd:element ref="Units" minOccurs="0"/>
				<xsd:element ref="Pieces" minOccurs="0"/>
				<xsd:element ref="ToWarehouse"/>
				<xsd:element ref="ToBin" minOccurs="0"/>
				<xsd:element ref="ToWhJournal" minOccurs="0"/>
				<xsd:element ref="Lot" minOccurs="0"/>
				<xsd:element ref="Reference" minOccurs="0"/>
				<xsd:element ref="Notation" minOccurs="0"/>
				<xsd:element ref="LedgerCode" minOccurs="0"/>
				<xsd:element ref="PasswordForLedgerCode" minOccurs="0"/>
				<xsd:element ref="Serials" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="SerialAllocation" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="eSignature" minOccurs="0"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="Journal">
		<xsd:annotation>
			<xsd:documentation>This is the journal number to which the transaction journal entries generated will be added. It must be valid for the specified posting period and warehouse and may not have been printed already. If not supplied, a new journal will be created.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:whiteSpace value="preserve"/>
				<xsd:minLength value="0"/>
				<xsd:maxLength value="5"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	<xsd:element name="LedgerCode">
		<xsd:annotation>
			<xsd:documentation>This element is only used if Inventory is integrated to General Ledger or requires a Report,  and ledger codes are required for this type of inventory transaction. If entered and used, it must be a valid ledger code, and must not be on hold.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:whiteSpace value="preserve"/>
				<xsd:minLength value="0"/>
				<xsd:maxLength value="15"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	<xsd:element name="Lot">
		<xsd:annotation>
			<xsd:documentation>This element is mandatory for lot traceable stock items. Not allowed for unit-qty type stock items.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:whiteSpace value="preserve"/>
				<xsd:minLength value="0"/>
				<xsd:maxLength value="10"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	<xsd:element name="NoDestination" default="N">
		<xsd:annotation>
			<xsd:documentation>If processing a warehouse transfer OUT No Destination, this element must contain 'Y'. If this is not supplied or is set to 'N' a normal transfer OUT transaction is processed.Defaults to 'N'. Valid values are 'N' and 'Y'.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:whiteSpace value="preserve"/>
				<xsd:minLength value="0"/>
				<xsd:maxLength value="1"/>
				<xsd:enumeration value="N"/>
				<xsd:enumeration value="Y"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	<xsd:element name="Notation">
		<xsd:annotation>
			<xsd:documentation>This element is optional.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:whiteSpace value="preserve"/>
				<xsd:minLength value="0"/>
				<xsd:maxLength value="45"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	<xsd:element name="PasswordForLedgerCode">
		<xsd:annotation>
			<xsd:documentation>If ledger codes require a password, this element must contain the relevant password for the specified ledger code.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:whiteSpace value="preserve"/>
				<xsd:minLength value="0"/>
				<xsd:maxLength value="30"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	<xsd:element name="Pieces">
		<xsd:annotation>
			<xsd:documentation>If stock item is a unit-qty type stock item and quantity element is not supplied, the quantity of the transaction must be supplied as units and pieces. At least one of these elements must be supplied.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:whiteSpace value="preserve"/>
				<xsd:minLength value="0"/>
				<xsd:maxLength value="3"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	<xsd:element name="Quantity">
		<xsd:annotation>
			<xsd:documentation>This element is mandatory if stock item is not a unit-qty type stock item. If it is and this element is supplied, the units and pieces elements must NOT be supplied.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:whiteSpace value="preserve"/>
				<xsd:minLength value="0"/>
				<xsd:maxLength value="11"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	<xsd:element name="Reference">
		<xsd:annotation>
			<xsd:documentation>This element is optional.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:whiteSpace value="preserve"/>
				<xsd:minLength value="0"/>
				<xsd:maxLength value="9"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	<xsd:element name="Release">
		<xsd:annotation>
			<xsd:documentation>This element is mandatory if stock is ECC-controlled at release level.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:whiteSpace value="preserve"/>
				<xsd:minLength value="0"/>
				<xsd:maxLength value="3"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	<xsd:element name="SerialLocation">
		<xsd:annotation>
			<xsd:documentation>Location of new serial if posting an immediate transfer and serial does not exist in destination warehouse.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:minLength value="0"/>
				<xsd:maxLength value="8"/>
				<xsd:whiteSpace value="preserve"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	<xsd:element name="SerialNumber">
		<xsd:annotation>
			<xsd:documentation>Serial number from which serial quantity must be transferred.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:whiteSpace value="preserve"/>
				<xsd:minLength value="1"/>
				<xsd:maxLength value="20"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	<xsd:element name="SerialQuantity">
		<xsd:annotation>
			<xsd:documentation>This element is mandatory and specifies the quantity to allocate for the specified serial number. If within the 'Serials' group and manual serial, it can only be 1 or -1. If within the 'SerialAllocation' group, it is the total quantity to be allocated for the specified range. The total quantity for all serial numbers specified must match the quantity specified for the transaction.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:whiteSpace value="preserve"/>
				<xsd:minLength value="0"/>
				<xsd:maxLength value="11"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	<xsd:element name="SerialUnits">
		<xsd:annotation>
			<xsd:documentation>If stock item is a unit-qty type stock item and serialquantity element is not supplied, the quantity of the transaction must be supplied as units and pieces. At least one of these elements must be supplied. This element is only valid for batch serialized items.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:minLength value="0"/>
				<xsd:maxLength value="7"/>
				<xsd:whiteSpace value="preserve"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	<xsd:element name="SerialPieces">
		<xsd:annotation>
			<xsd:documentation>If stock item is a unit-qty type stock item and serialquantity element is not supplied, the quantity of the transaction must be supplied as units and pieces. At least one of these elements must be supplied. This element is only valid for batch serialized items.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:minLength value="0"/>
				<xsd:maxLength value="3"/>
				<xsd:whiteSpace value="preserve"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	<xsd:element name="Serials">
		<xsd:annotation>
			<xsd:documentation>A set of serial numbers and relevant quantities to process may be supplied, if stock item is serialized. Not allowed for unit-qty type stock items.</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType mixed="false">
			<xsd:sequence>
				<xsd:element ref="SerialNumber"/>
				<xsd:element ref="SerialQuantity" minOccurs="0"/>
				<xsd:element ref="SerialUnits" minOccurs="0"/>
				<xsd:element ref="SerialPieces" minOccurs="0"/>
				<xsd:element ref="SerialLocation" minOccurs="0"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="SerialAllocation">
		<xsd:annotation>
			<xsd:documentation>This element is used to specify a range of serial numbers to be allocated. It is only valid when processing manual serialized stock items.</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType mixed="false">
			<xsd:sequence>
				<xsd:element ref="FromSerialNumber"/>
				<xsd:element ref="ToSerialNumber" minOccurs="0"/>
				<xsd:element ref="SerialQuantity"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="FromSerialNumber">
		<xsd:annotation>
			<xsd:documentation>This element specifies the starting serial number to be allocated.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:minLength value="1"/>
				<xsd:maxLength value="20"/>
				<xsd:whiteSpace value="preserve"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	<xsd:element name="ToSerialNumber">
		<xsd:annotation>
			<xsd:documentation>This element specifies the ending serial number to be allocated. If this element is not supplied, serial numbers will be allocated starting at the FromSerialNumber until the specified quantity has been allocated.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:minLength value="0"/>
				<xsd:maxLength value="20"/>
				<xsd:whiteSpace value="preserve"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	<xsd:element name="StockCode">
		<xsd:annotation>
			<xsd:documentation>This element is mandatory and must be stocked in 'From' warehouse specified.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:whiteSpace value="preserve"/>
				<xsd:minLength value="1"/>
				<xsd:maxLength value="30"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	<xsd:element name="ToBin">
		<xsd:annotation>
			<xsd:documentation>This element is mandatory if multiple bins are installed. If transaction is an 'Immediate' transfer, this bin location must exist in the 'To' warehouse.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:whiteSpace value="preserve"/>
				<xsd:minLength value="0"/>
				<xsd:maxLength value="6"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	<xsd:element name="ToWarehouse">
		<xsd:annotation>
			<xsd:documentation>This element is mandatory unless transaction is a 'No Destination' transfer. Stock item specified must be stocked in this warehouse unless 'CreateDestinationWarehouse' paramenter is set to 'Y'. In this case, the warehouse will be created for this stock item.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:whiteSpace value="preserve"/>
				<xsd:minLength value="1"/>
				<xsd:maxLength value="2"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	<xsd:element name="ToWhJournal">
		<xsd:annotation>
			<xsd:documentation>This is the journal number to which the journal entry generated for the receiving warehouse on an immediate transfer will be added. It must be valid for the specified posting period and receiving warehouse and may not have been printed already. If not supplied, a new journal will be created.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:minLength value="0"/>
				<xsd:maxLength value="5"/>
				<xsd:whiteSpace value="preserve"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	<xsd:element name="UnitOfMeasure">
		<xsd:annotation>
			<xsd:documentation>If quantity was supplied in a unit of measure different to the stocking unit of measure, this element may be supplied to indicate the alternate unit of measure.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:whiteSpace value="preserve"/>
				<xsd:minLength value="0"/>
				<xsd:maxLength value="3"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	<xsd:element name="Units">
		<xsd:annotation>
			<xsd:documentation>If stock item is a unit-qty type stock item and quantity element is not supplied, the quantity of the transaction must be supplied as units and pieces. At least one of these elements must be supplied.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:whiteSpace value="preserve"/>
				<xsd:minLength value="0"/>
				<xsd:maxLength value="7"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	<xsd:element name="Version">
		<xsd:annotation>
			<xsd:documentation>This element is mandatory if stock is ECC-controlled at version or release level.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:whiteSpace value="preserve"/>
				<xsd:minLength value="0"/>
				<xsd:maxLength value="3"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
</xsd:schema>

=== Zarconium/Senior/CS119.2 ESP/Inventory Posting Functional Area/Transfers/Transfer OUT/INVTMODOC.XML
<?xml version="1.0" encoding="Windows-1252"?>
<!-- Copyright 1994-2010 SYSPRO Ltd.-->
<!-- 
     This is an example XML instance to demonstrate
     use of the Inventory Warehouse Transfer Out Business Object
-->
<PostInvWhTransferOut xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="INVTMODOC.XSD">
  <Item>
    <Journal/>
    <Immediate>N</Immediate>
    <NoDestination>N</NoDestination>
    <FromWarehouse>E</FromWarehouse>
    <FromBin>E1</FromBin>
    <StockCode>A100</StockCode>
    <Version/>
    <Release/>
    <Quantity>4</Quantity>
    <UnitOfMeasure/>
    <Units/>
    <Pieces/>
    <ToWarehouse>N</ToWarehouse>
    <ToBin>N1</ToBin>
    <ToWhJournal></ToWhJournal>
    <Lot/>
    <Reference>Xfer OUT</Reference>
    <Notation>WH transfers</Notation>
    <LedgerCode>30-1540</LedgerCode>
    <PasswordForLedgerCode/>
    <Serials>
      <SerialNumber>BCS11495</SerialNumber>
      <SerialQuantity>1</SerialQuantity>
      <SerialUnits/>
      <SerialPieces/>
      <SerialLocation/>
    </Serials>
    <SerialAllocation>
      <FromSerialNumber>BCS11497</FromSerialNumber>
      <ToSerialNumber>BCS11499</ToSerialNumber>
      <SerialQuantity>3</SerialQuantity>
    </SerialAllocation>
    <eSignature/>
  </Item>
</PostInvWhTransferOut>
